namespace EmuEzInputConfig.ConfigWriters;

using EmuEzInputConfig.Models;

/// <summary>
/// Generates and deploys DevReorder config (devreorder.ini + dinput8.dll)
/// to emulator directories.
/// </summary>
public class DevReorderDeployer
{
    /// <summary>
    /// Target directories for DevReorder deployment (relative to LaunchBox root).
    /// </summary>
    private static readonly (string RelativePath, string Name)[] Targets =
    [
        (@"Emulators\PCSX2", "PCSX2"),
        (@"Emulators\Sega Model 3", "Supermodel"),
        (@"Emulators\DuckStation", "DuckStation"),
        (@"Emulators\ppsspp", "PPSSPP"),
        (@"Emulators\rpcs3", "RPCS3"),
    ];

    /// <summary>
    /// Generate devreorder.ini content.
    /// </summary>
    public static string GenerateIni(InputConfig config)
    {
        string wheelName = config.Wheel?.ProductName ?? "Unknown Wheel";
        string shifterName = config.Shifter?.ProductName ?? "VelocityOne Multi-Shift";
        string? gamepadName = config.GamepadToHide;

        var lines = new List<string>
        {
            $"; Generated by EmuEzInputConfig on {DateTime.Now:yyyy-MM-dd HH:mm:ss}",
            "; Re-run the app if hardware changes.",
            "",
            "[order]",
            shifterName,
            wheelName,
            "",
            "[hidden]",
        };

        if (!string.IsNullOrEmpty(gamepadName))
            lines.Add(gamepadName);
        else
            lines.Add("Controller (XBOX 360 For Windows)");

        return string.Join("\r\n", lines);
    }

    /// <summary>
    /// Deploy devreorder.ini and dinput8.dll to all target emulator directories.
    /// Returns a list of (target, success, message) results.
    /// </summary>
    public static List<(string Target, bool Success, string Message)> Deploy(
        string launchboxRoot, InputConfig config)
    {
        var results = new List<(string, bool, string)>();
        string iniContent = GenerateIni(config);

        // Source DLL from PCSX2 directory (should already be there from initial setup)
        string sourceDll = Path.Combine(launchboxRoot, @"Emulators\PCSX2\dinput8.dll");

        foreach (var (relPath, name) in Targets)
        {
            string targetDir = Path.Combine(launchboxRoot, relPath);
            if (!Directory.Exists(targetDir))
            {
                results.Add((name, false, $"Directory not found: {targetDir}"));
                continue;
            }

            try
            {
                // Write INI
                string targetIni = Path.Combine(targetDir, "devreorder.ini");
                File.WriteAllText(targetIni, iniContent);

                // Copy DLL if source exists and target is different or missing
                string targetDll = Path.Combine(targetDir, "dinput8.dll");
                if (File.Exists(sourceDll))
                {
                    if (!File.Exists(targetDll) || !FilesEqual(sourceDll, targetDll))
                    {
                        File.Copy(sourceDll, targetDll, overwrite: true);
                        results.Add((name, true, "Deployed devreorder.ini + dinput8.dll"));
                    }
                    else
                    {
                        results.Add((name, true, "Deployed devreorder.ini (DLL already up to date)"));
                    }
                }
                else
                {
                    results.Add((name, true, "Deployed devreorder.ini (source DLL not found)"));
                }
            }
            catch (Exception ex)
            {
                results.Add((name, false, ex.Message));
            }
        }

        return results;
    }

    private static bool FilesEqual(string path1, string path2)
    {
        var info1 = new FileInfo(path1);
        var info2 = new FileInfo(path2);
        return info1.Length == info2.Length;
    }
}
