namespace EmuEzInputConfig.Tests.ConfigWriters;

using EmuEzInputConfig.ConfigWriters;
using EmuEzInputConfig.Tests.TestHelpers;

public class DevReorderDeployerTests
{
    [Fact]
    public void GenerateIni_DefaultConfig_ContainsOrderAndHiddenSections()
    {
        var config = InputConfigBuilder.MozaR12().Build();
        string ini = DevReorderDeployer.GenerateIni(config);

        Assert.Contains("[order]", ini);
        Assert.Contains("[hidden]", ini);
    }

    [Fact]
    public void GenerateIni_DefaultConfig_WheelInOrder()
    {
        var config = InputConfigBuilder.MozaR12().Build();
        string ini = DevReorderDeployer.GenerateIni(config);

        Assert.Contains("MOZA Racing R12", ini);
    }

    [Fact]
    public void GenerateIni_DefaultConfig_DefaultShifterInOrder()
    {
        var config = InputConfigBuilder.MozaR12().Build();
        string ini = DevReorderDeployer.GenerateIni(config);

        // No shifter specified → default "VelocityOne Multi-Shift"
        Assert.Contains("VelocityOne Multi-Shift", ini);
    }

    [Fact]
    public void GenerateIni_NoGamepad_DefaultGamepadHidden()
    {
        var config = InputConfigBuilder.MozaR12().Build();
        string ini = DevReorderDeployer.GenerateIni(config);

        Assert.Contains("Controller (XBOX 360 For Windows)", ini);
    }

    [Fact]
    public void GenerateIni_CustomGamepad_CustomNameHidden()
    {
        var config = InputConfigBuilder.MozaR12()
            .WithGamepadToHide("Xbox One Controller")
            .Build();
        string ini = DevReorderDeployer.GenerateIni(config);

        Assert.Contains("Xbox One Controller", ini);
        Assert.DoesNotContain("Controller (XBOX 360 For Windows)", ini);
    }

    [Fact]
    public void GenerateIni_CustomProductName_AppearsInOutput()
    {
        var config = InputConfigBuilder.MozaR12()
            .WithProductName("Fanatec CSL DD")
            .Build();
        string ini = DevReorderDeployer.GenerateIni(config);

        Assert.Contains("Fanatec CSL DD", ini);
        Assert.DoesNotContain("MOZA Racing R12", ini);
    }

    [Fact]
    public void GenerateIni_NullWheel_FallsBackToUnknown()
    {
        var config = InputConfigBuilder.MozaR12().Build();
        config.Wheel = null;
        string ini = DevReorderDeployer.GenerateIni(config);

        Assert.Contains("Unknown Wheel", ini);
    }

    [Fact]
    public void GenerateIni_OrderSection_ShifterBeforeWheel()
    {
        var config = InputConfigBuilder.MozaR12().Build();
        string ini = DevReorderDeployer.GenerateIni(config);

        int shifterPos = ini.IndexOf("VelocityOne Multi-Shift");
        int wheelPos = ini.IndexOf("MOZA Racing R12");
        Assert.True(shifterPos < wheelPos, "Shifter should appear before wheel in [order]");
    }

    [Fact]
    public void GenerateIni_ContainsTimestamp()
    {
        var config = InputConfigBuilder.MozaR12().Build();
        string ini = DevReorderDeployer.GenerateIni(config);

        Assert.Contains("; Generated by EmuEzInputConfig on", ini);
    }
}
